# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198IooJV0g0OuUDBwfMVbJENODyefnKb4
"""

from sklearn.datasets import load_digits
digits = load_digits()

digits

digits.data

digits.target



# Print to show there are 1797 images (8 by 8 images for a dimensionality of 64)
print("Image Data Shape" , digits.data.shape)
# Print to show there are 1797 labels (integers from 0–9)
print("Label Data Shape", digits.target.shape)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.25, random_state=0)

from sklearn.linear_model import LogisticRegression

# all parameters not specified are set to their defaults
logisticRegr = LogisticRegression()

logisticRegr.fit(x_train, y_train)

predictions = logisticRegr.predict(x_test)
predictions

# Use score method to get accuracy of model
score = logisticRegr.score(x_test, y_test)
print(score)

from sklearn import metrics

cm = metrics.confusion_matrix(y_test, predictions)
print(cm)